# Generated by Django 4.0.2 on 2022-03-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_orderitem_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='image',
        ),
    ]
